platform:
  - x86
  - x64

environment:
  nodejs_version: "8.9.1"

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

test_script:
  - node --version
  - npm --version

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

build_script:
  - npm run dist