platform:
  - x86
  - x64

environment:
  nodejs_version: "8.9.1"

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

test_script:
  - node --version
  - npm --version

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

build_script:
  - npm run build

deploy:
  release: gelbooru-client
  provider: GitHub
  auth_token:
    secure: oZGyi7pPIdF3lFXXRpaWxxoLpakgUXdBKLmi3VlUGFFvdEQ6MzTNEPGspNOHWFbb
  artifact: /gelbooruClient.exe/
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true